### ISSUE TITLE
Italian translation not displaying on book page

### ISSUE THREAD

**Issue by MichSpieler** [pressbooks/pressbooks-book#1260]
### Description

A network manager who has contributed extensively to the Italian localization on Transifex has reported that translations are not showing up as expected.
For example, when a book's language is set to Italian, the strings on the book's webpage still appear in English:
<img width="530" alt="image" src="https://github.com/user-attachments/assets/99dbd168-8765-4310-a2c4-97a986741455">
"All Rights Reserved" and "Read Book" should appear in Italian.

The translation is present in McLuhan / pressbooks-book on Transifex:
<img width="707" alt="image" src="https://github.com/user-attachments/assets/30ccc831-01c8-4cd2-b3ba-7665d5dffaf7">
<img width="714" alt="image" src="https://github.com/user-attachments/assets/9e010909-82ea-45ca-a632-99a60c021546">
It is also present in pressbooks-book/languages/it_IT.po:
<img width="471" alt="image" src="https://github.com/user-attachments/assets/f9f130c0-671b-4bac-94a2-93cf38487de3">
<img width="355" alt="image" src="https://github.com/user-attachments/assets/ed3641f6-7e22-4fa0-893f-b61cd13c948d">

100% of McLuhan is translated to Italian.
46% of Pressbooks is translated to Italian.

I have compared this to what happens when setting the book language to Spanish (works as expected) and to German (does not display translation) as well.

I found the "Leer el libro" string in three .po files:
<img width="587" alt="image" src="https://github.com/user-attachments/assets/b6e5a79e-003c-4cc7-a7f9-055e293fcef8">

For German I found "Buch lesen" only in 2 files:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/885d297d-c819-4cc6-ad94-0a414e188cb6">
<img width="487" alt="image" src="https://github.com/user-attachments/assets/992d685c-6ce5-420f-8b5a-a4f95be2857d">

For Italian I found "Leggi il libro" only in 1 file:
<img width="510" alt="image" src="https://github.com/user-attachments/assets/20c6b7f7-b4bc-4e43-b23a-44cd6840af16">

**Comment by cmurtagh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks-book/1260?planning-poker) with Zenhub @arzola @fdalcin @ho-man-chan @richard015ar @tw77

**Comment by frankjmueller** [comment]
Thank you for adding this. German works for me. Weird.

**Comment by SteelWagstaff** [comment]
I believe this is happening because there is no it_IT.mo file in the languages folder. WordPress needs the machine readable translation files. We typically generate a .po file for the translation, but I suspect that the automation we've built to handle translation updates doesn't commit new .mo files the first time they're created. The Italian language .po file was added in July 2024, but the action that was supposed to update the .mo file failed: https://github.com/pressbooks/pressbooks-book/actions/runs/9666155056.

It failed because it's pointing to `update-mo.yml@dev` but there is only a `main` branch for that repo: https://github.com/pressbooks/reusable-workflows/branches

**Comment by SteelWagstaff** [comment]
This PR should fix the workflow? https://github.com/pressbooks/pressbooks-book/pull/1262

**Comment by cmurtagh** [comment]
These PRs seem to have resolve this issue.

**Comment by SteelWagstaff** [comment]
Did we test and confirm on the dev networks? I was going to wait for autodeploy before testing ...

**Comment by SteelWagstaff** [comment]
Works as expected on dev.pressbooks.network:
![Screenshot from 2024-09-30 10-44-43](https://github.com/user-attachments/assets/1142a9bb-6ac0-439d-8007-0f17ea7d0e40)

**Comment by frankjmueller** [comment]
Awesome. Thank you!

**Comment by SteelWagstaff** [comment]
@frankjmueller this should be included in our next release of the McLuhan theme. You can follow the release notes here, or we can let you know when it's been deployed to your production network.

**Comment by frankjmueller** [comment]
Will this thread be updated (automatically) if it is released? Then I am fine. :)

**Comment by fdalcin** [comment]
@frankjmueller the ticket is not automatically updated. The fix should be included in the [v2.26.5](https://github.com/pressbooks/pressbooks-book/releases/tag/2.26.5) release of McLuhan theme which was released today.

**Comment by frankjmueller** [comment]
Hi,
thank you. I have checked and in the themes section McLuhan is shown as 2.26.5.

I still get the "Please contact your system administrator if you would like them to install extended Italian language support for the Pressbooks interface." notice when I try to activate italian in the language settings. (I tried to switch to English and back to Italian.

<img width="1013" alt="grafik" src="https://github.com/user-attachments/assets/ba00c71f-17b2-4927-b0a5-b91c226ec530">

Is there something I can check? Best wishes
Frank J.

**Comment by cmurtagh** [comment]
I'll ask our devs about this.

**Comment by SteelWagstaff** [comment]
hi @frankjmueller -- if you change the book language to Italian in book information, the publicly displayed information on the book's home page will in fact display the available strings in Italian. You can see this on this book, for example: https://university.pressbooks.pub/french102/. 

I just checked the All Means All network and also see both the authoring interface and the book metadata on your book: https://book.all-means-all.education/ama-2025-it/ appearing in Italian. Are you ok with us closing this issue as resolved?

**Comment by SteelWagstaff** [comment]
You can safely ignore the "Please contact your system administrator if you would like them to install extended Italian language support for the Pressbooks interface." notice at the top of the page -- that is being displayed simply because the full Italian language pack for WordPress is not installed for your network. Our enterprise networks are installed with English/French as the available administrative languages, as these are the primary working languages used by our enterprise clients, but I believe that additional languages can be installed upon request. Generally these are only needed if a user would like to change their administrative interface to ALWAYS display available text in that language even if the book is set to use a different language.

As currently configured, when a user changes the Book Language to something other than the default, all of the available strings in the book admin interface and the homepage of the book are set to display in that language, UNLESS the user has set the language settings in their user profile to a preferred language (i.e. English or French). The default user profile setting is 'Site Default'. 
![Screenshot from 2024-10-16 16-02-44](https://github.com/user-attachments/assets/de5527ff-4aac-44c6-a54b-90dd7451cff1)

This can be a little confusing, but these guide chapters might help: 
https://guide.pressbooks.com/chapter/support-multilingual-publications/ + https://guide.pressbooks.com/chapter/update-your-user-profile/#language

**Comment by arzola** [comment]
Waiting for client feedback

**Comment by frankjmueller** [comment]
Hi, it works now. Thank you!
