### ISSUE TITLE
Side-Aligned images cause large margins to appear on bottom of preceding page in PDF export

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#459]
### Description
Images that will not fit at the bottom of one page will automatically move to the next page. However, when that image is right- or left-aligned, the text that is wrapped around the images goes with it to the next page, resulting in large amounts of blank space at the bottom of the page before. 

Example: https://testbooknormaluser.textopress.com/chapter/text-wrap-around-side-aligned-images/
![screen shot 2019-01-09 at 3 57 57 pm](https://user-images.githubusercontent.com/39064028/50927981-57c02100-1427-11e9-87a4-1b8508eac931.png)

### Steps to Reproduce

1. Create a new chapter in your book
2. Paste some sample text into the chapter, and add an image
3. Select the image in the visual editor, then choose "Align left" from the setting options that appear
4. Save the chapter and export as a PDF 

Note: The image does have to be at the top of the page for the error to occur. If the image is not at the top of the page, delete the text between the aligned image and the top of its current page, as well as a small amount of text (smaller than the image) from the page before. 

**Expected behavior:** If a side-aligned image does not fit on the preceding page, the paragraph approximate to it should continue on the preceding page. Text should only wrap around an image on the page an image appears on. 

**Actual behavior:** Side-aligned images at the tops of pages can prevent text from flowing from page to page and cause large margins.

Book URL: http://testbooknormaluser.textopress.com/

**Comment by greatislander** [comment]
I could be wrong but I think this may be how Prince behaves. To investigate further.

**Comment by dannylonglegs** [comment]
![screenshot 2 _li](https://user-images.githubusercontent.com/21149722/51916086-91db6d80-23aa-11e9-9a61-0a0c3a1b44c2.jpg)

The issue is shown above. In the editor, there is a non-breaking space (or "&nbsp;") that is adding an extra paragraph element before the aligned image. It can be seen in the text editor below. This issue is resolved when that extra non breaking space is removed. 
![sidealignspaceissue](https://user-images.githubusercontent.com/21149722/51916093-94d65e00-23aa-11e9-864d-a965bfc15b93.JPG)

**Comment by SteelWagstaff** [comment]
Needs further refinement.
