### ISSUE TITLE
PDF: Media Fallback textbox images inherit an unwanted indent

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-book#476]
### Description

Media fallback textbox images inherit a text indent from regular textbox styles. This inherited style is not overwritten by the media fallback text indent style. This needs to be fixed.

**Comment by mcgratay** [comment]
Confirmed as reproducible. Tested in: McLuhan, Asimov, and Clarke. 

Notes: 
- Does seem to affect both ebook and PDF formats. 
- Issue didn't appear in the Malala theme, but did appear in all other tested Buckram themes
- Paragraph Separation setting must be set to Indent 

Example: https://fallbacktextindent.textopress.com/

**Comment by SteelWagstaff** [comment]
Can add `text-indent: 0` here: https://github.com/pressbooks/pressbooks-book/blob/f589836a346f1d1950aad2bf1adb5229f3ddfa90/assets/legacy/styles/_textboxes.scss#L101-L103? Could potentially be fixed by solution described in https://github.com/pressbooks/pressbooks-book/issues/355#issuecomment-812925481

**Comment by SteelWagstaff** [comment]
Tested and working as expected on integrations
