### ISSUE TITLE
Spacing not consistent in collapsed sections in a webbook

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#542]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description
When a user has added multiple H1s to a chapter and enabled the collapsed section setting for the webbook, collapsed section headings are not consistently spaced. 

Example: https://collapsedsectionerrors.textopress.com/chapter/chapter-1/

### Steps to Reproduce

1. Create a new book or access an existing one on Pressbooks
2. Add content with multiple headings tagged with paragraph style h1 strewn throughout and save your chapter
3. Go to **Appearance > Theme Options > Web Options** and enable the Collapse Sections setting, then save changes
4. View your webbook to see if collapsed section headings are evenly spaced

**Expected behavior:** Each collapsed section is equally spaced from the others

**Actual behavior:** Collapsed section headings are spaced inconsistently in some cases

**Comment by SteelWagstaff** [comment]
I took a quick look at the example you shared, Taylor. We have a CSS rule that zeros out the top margins for `.back-matter div[hidden]+h1:not(:first-of-type), .chapter div[hidden]+h1:not(:first-of-type), .front-matter div[hidden]+h1:not(:first-of-type), .part div[hidden]+h1:not(:first-of-type)`. In this case, however, the text has produced two `.section` divs, each with multiple h1s. Because the CSS rule just cited only applies to h1 elements which are _not_ `first-of-type,` the first h1 in each of these divs still has a margin-top of 2.1428571429em (set by a rule targeting `.chapter h1` elements). 
![Screen Shot 2019-05-13 at 8 56 54 AM](https://user-images.githubusercontent.com/13485451/57627251-41ed7480-755d-11e9-9b32-f53e9075d15a.png)

I don't know why these h1s are being put into different divs, but if we can fix that, the display issue should also be fixed.

**Comment by SteelWagstaff** [comment]
I think this issue was the result of the user having (or adding) additional `div` elements to the text (in this case they were `.bc-section` divs. I'm guessing that this may have been something that BCcampus added to their original book and which the user inherited when they cloned/copied the book to their own network. In the textopress example you shared, I was able to fix the spacing issue by going into the source HTML and removing the superfluous divs from the book. In other word, I don't think these divs weren't created by some glitch in the WYSIWYG, but by intentional user choice, and that choice impacted how our CSS rendered the collapsed sections, because of the first-child pseudo selector. I'm going to close this issue as something that we're not going to 'fix,' though we could document the workaround for this anomaly in our documentation if desired (i.e. remove extra divs from the HTML source of a document that is styling strangely).
